config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show, :edit, :update] do
    get :my_reservations
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :listings do
    collection do
      get :my_listings
    end
    resources :reservations, only: [ :index, :new, :create, :show ]
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  TYPE = ["Campervan", "Tent", "Cooker", "Technology", "Gear", "Survival Kit", "Backpack", "Other"]

  has_many :reservations

  validates :name, :price, :location, presence: true
  validates :description, presence: :true, length: { minimum: 10 }
  validates :equipment_type, presence: true, inclusion: { in: TYPE }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  
  has_many :reservations, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index

     # refers to the listing_policy and resolce method
    @user = current_user

    @listings = policy_scope(Listing)

    @search = params["search"]
    if @search.present?
      @location = @search["location"]
      @listings = @listings.where("location ILIKE ?", "%#{@location}%")
    end

    @markers = @listings.geocoded.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude
      }
    end
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      flash[:success] = "Listing successfully created"
      redirect_to listing_path(@listing)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end


  def show

    @listing_user = @listing.user
    @reservation = Reservation.new

  end


  def edit

    authorize @listing
  end

  def update
    if @listing.update(listing_params)
      redirect_to listing_path(@listing)
    else
      render :edit
    end
    authorize @listing
  end

  def destroy
    @listing.destroy
    redirect_to listings_path
  end

  def my_listings
    @listings = Listing.where(user_id: current_user)
    # @reservations = Reservation.where(id: listing_id)
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def listing_params
    params.require(:listing).permit(:name, :description, :price, :equipment_type, :location, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_listing, only: [:index, :create, :show]

  def index
    @reservations = policy_scope(Reservation) # refers to the reservation_policy and resolce method
  end

  def new
    @reservations = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    # so the reservation has the same user as current_user, it's not authomatic
    @reservation.user = current_user
    # to pass "parameters" from current listing to the reservation listing parameters
    @reservation.listing = @listing

    if @reservation.save
      flash[:success] = "Reservation successfully created"
      # tis is path for the confirmation of reservation, takes both the listing and reservation
      redirect_to listing_reservation_path(@listing, @reservation)
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def show # to be able see reservation oin the show (in the view show we do the confirmation)
    @reservation = Reservation.find(params[:id])
  end

  private

  def set_listing
    @listing = Listing.find(params[:listing_id]) # fint the id of the listing
  end

  def reservation_params
    params.require(:reservation).permit(:starts_at, :ends_at)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "User was successfully updated"
        redirect_to @user
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end

  def my_reservations
    @reservations = Reservation.where(user_id: current_user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :email, :avatar, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CamperWorld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= simple_form_for @listing do |f| %>
  <%= f.label :name, 'Name' %>
  <%= f.input :name, label: false%>
  <%= f.label :description, 'Description (min. 10 char)' %>
  <%= f.input :description, label: false%>
  <%= f.label :price, 'Price' %>
  <%= f.input :price, label: false%>
  <%= f.label :equipment_type, 'Equipment' %>
  <%= f.input :equipment_type, label: false, collection: Listing::TYPE %>
  <%= f.label :location, 'Location (city)' %>
  <%= f.input :location, label: false %>
  <%= f.input :photo, as: :file %>
  <div class="d-flex justify-content-between align-items-center btn">
    <%= link_to icon('fas', 'times', "Cancel"), listings_path, class: "btn" %>
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="text-center">Editing Listing <%= @listing.name %> </h1>
  </div>
  <div class="row justify-content-center">
    <div class="col-8 col-lg-6">
        <%= render 'form', listing: @listing %>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<header>
  <div class="container mt-5" justify-content-center>
     <h1>
       <% if @search %>
        <%= "Available listings in #{params[:search]["location"]}" %>
       <% else %>
        <%= "All available listings" %>
       <% end %>
    </h1>

  </div>
</header>

<br>

<main>

  <div class="container" >
    <%= simple_form_for :search, url: listings_path, method: "GET" do |f| %>
      <div class="search-form-control form-group">
        <%= f.input :location, input_html: {value: "" , class: "form-control string required", autocomplete: "off"  }, placeholder: "search for another location", type:"text", name:"search[query]", id:"search_query", label: false %>
        <%= button_tag type: "submit", id: "search_btn" do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
    <% end %>
    <br>

    <div class="row">
      <% @listings.each do |listing| %>
        <div class="col col-sm-6 col-lg-4">
          <%= link_to listing_path(listing) do %>
            <div class="card-trip" id="listing_card">
              <% if listing.photo.attached? %>
                <%= cl_image_tag listing.photo.key %>
              <% else %>
                <%= image_tag(listing.listing_photo)%>
              <% end %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= listing.name %> | <%= listing.location %></h2>
                  <p><%= listing.description %></p>
                  <p><small><%= icon('fas', 'hashtag') %> <%= listing.equipment_type %></small></p>
                </div>
                <h2 class="card-trip-pricing">€<%= listing.price %></h2>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div id="map" class="mt-5"
       style="width: 100%; height: 600px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>


</main>

app/views/listings/my_listings.html.erb
<div class="container mt-5" justify-content-center>
    <h1><%= current_user.first_name %>, here are all your listings: </h1>
</div>

<main>
  <div class="container" >
    <div class="row">
      <% @listings.each do |listing| %>
        <div class="col-6">
            <div class="card-trip">
              <% if listing.photo.attached? %>
                <%= cl_image_tag listing.photo.key %>
              <% else %>
                <%= image_tag(listing.listing_photo)%>
              <% end %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= listing.name %> | <%= listing.location %> | €<%= listing.price %></h2>
                  <p><%= listing.description %></p>
                  <hr>
                  <p class="text-danger">Reservations for this listing: </p>
                  <% listing.reservations.each do |reservation| %>
                    <p>From <%= reservation.starts_at %> till <%= reservation.ends_at %></p>
                  <% end %>
                </div>
                <div class="d-flex align-items-start">
                  <%= link_to icon('fas fa-edit', "Edit"), edit_listing_path(listing), class: "btn pt-0 pr-0 text-muted" %>
                  <%= link_to icon('fas fa-trash', 'Delete'), listing_path(listing), method: :delete, data: { confirm: "Are you sure you want to completely delete #{listing.name}?"}, class: "btn pt-0 pr-0 text-muted" %>
                </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/listings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="text-center">Create new listing</h1>
  </div>
  <div class="row justify-content-center">
    <div class="col-8 col-lg-6">

      <%= render 'form', listing: @listing %>

    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container mt-5">
  <div class="row align-items-center mb-3">
    <div class="col-2">
      <p><%= link_to icon('fas', 'chevron-left', "Back"), :back, class: "btn" %></p>
    </div>
    <div class="col-8">
      <h1 class="text-center"><strong><%= @listing.name %></strong></h1>
    </div>
    <% if @user == @listing_user %>
      <div class ="showBtn col-2">
        <%= link_to icon('fas fa-edit', "Edit"), edit_listing_path(@listing),class: "btn btn-flat"%>
        <%= link_to icon('fas fa-trash', 'Delete'), listing_path, method: :delete, data: { confirm: "Are you sure you want to completely delete #{@listing.name}?"}, class: "btn btn-flat" %>
      </div>
    <% end%>
  </div>

  <div class="row justify-content-center">
    <div class="col-sm-6 col-lg-4">
      <% if @listing.photo.attached? %>
        <%= cl_image_tag @listing.photo.key, class: "img-responsive", width: "100%" %>
      <% else %>
        <%= image_tag(@listing.listing_photo, class: "img-responsive", width: "100%") %>
      <% end %>
      <div id="listing-owner" class="d-flex align-items-center mt-3">
        <div>
          <% if @listing.user.avatar.attached? %>
            <%= cl_image_tag @listing.user.avatar.key, class: "avatar-large" %>
          <% else %>
            <img src="https://medgoldresources.com/wp-content/uploads/2018/02/avatar-placeholder-300x300.gif" alt="user-avatar" class="avatar-large">
          <% end %>
        </div>
        <div class="pl-2">
          <strong>Owner:</strong> <%= @listing.user.first_name %>
          <br>
          <strong>Phone number:</strong> <%= @listing.user.phone_number %>
        </div>
      </div>
    </div>
    <div class="listing-info col-sm-6 col-lg-4">
      <p><%= icon('fas', 'map-marker-alt') %> <%= @listing.location %> | <strong>€<%= @listing.price %></strong> per night</p>
      <p></p>
      <p><small><%= icon('fas', 'hashtag') %> <%= @listing.equipment_type %></small></p>
      <p><%= @listing.description %></p>
      <div class="reservation-box">
        <h3><small>Reserve now:</small></h3>
        <%= simple_form_for ([@listing, @reservation]) do |f| %>
          <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker", id: "range_start"} %>
          <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker", id: "range_end"} %>
          <%= f.button :submit, "Reserve", class: "btn", id: "btn-all", data: { confirm: "Are you sure you want to make the reservation?"}%>        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class ="homecontainer" style="background-image: url(<%= asset_path 'home.jpg' %>)">
  <div class="container">
    <h1 id="tagline">Whatever your outdoor heart desires: <span id="banner-typed-text"></span></h1>

    <h5 id="intro">Going on an adventure? Rent all the camping gear you need for your next trip! </h5>

    <%= simple_form_for :search, url: listings_path, method: "GET" do |f| %>
      <div class="search-form-control form-group" id="searchbar">
        <%= f.input :location, input_html: {value: "" , class: "form-control string required", autocomplete: "off" }, placeholder: "search for a location", type:"text", name:"search[query]", id:"search_query" %>
        <%= button_tag type: "submit", id: "search_btn" do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
    <% end %>

    <br>
    <div id="view_btn">
      <%= link_to "view all", listings_path, class: "btn btn-flat", id: "btn-all" %>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<h1> This are all the Reservations for product: <%= @reservation %></h1>
<p>link to the page you're on --->
<%= link_to "all reservation", listing_reservations_path(@listing) %>
</p>

<p>link to the page reservations show --->
<%= link_to "show reservation", listing_reservations_path(@listing) %>
</p>

app/views/reservations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <p> Dates selected: </p>
      <%= link_to "Cancel", :back %>
      <%= link_to "Confirm" %>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<!-- LOGIC for this -->

<!-- on this page will be shown the confirmation of the reservation -->
<!-- so the confirmation in in the show and not in the new in reservations, because new is always the for  -->
<!-- and we have the form in listings/id -->
<!-- we need to redirect to the listing show so we can display the listings and the reservation in one show -->
<!-- in the listing show the reserrvation data is available thanks to the definition in the lisitngs show controller -->

<!-- be careful -> the presentation schema has changed, now we are using 2 dates and not one -->


<!-- there should be something like destroy or proceed -->


<!-- <p>listing id: <%= @listing.id %> </p>
<p>reservation id: <%= @reservation.id %> </p>
 -->


<div class="container">
  <div class="row align-items-center mb-3">
    <div class="col-2">
    </div>
    <div class="col-8 mt-5">
      <h1 class="text-center"><strong>Reservation confirmed ✅</strong></h1>
      <h2 class="text-center">Camper: <%= @listing.name %></h2>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-4">
      <% if @listing.photo.attached? %>
        <%= cl_image_tag @listing.photo.key, class: "img-responsive", width: "100%" %>
      <% else %>
        <%= image_tag(@listing.listing_photo, class: "img-responsive", width: "100%") %>
      <% end %>
    </div>
    <div class="listing-info col-4">
      <p><%= icon('fas', 'map-marker-alt') %> <%= @listing.location %></p>
      <p><strong><%= @listing.price %>€</strong></p>
      <p><%= icon('fas', 'hashtag') %> <%= @listing.equipment_type %></p>
      <p>booked from: <strong><%= @reservation.starts_at %></strong> to: <strong><%= @reservation.ends_at %></strong></p>
      <p><%= link_to "My Reservations", user_my_reservations_path(current_user),class: "btn", id: "btn-all" %></p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= icon('fas', 'campground') %>
    <span>Camperworld</span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li><%= link_to icon('fas', 'plus', 'New listing'), new_listing_path, class: "nav-link" %></li>
        <li><%= link_to icon('fas', 'comments', 'Messages'), "#", class: "nav-link" %></li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My Reservations", user_my_reservations_path(current_user), class: "dropdown-item" %>
            <%= link_to "My Listings", my_listings_listings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-5">
  <%= simple_form_for current_user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
    <%= f.input :avatar, as: :file %>
    <%#= f.input :location %>
    <div class="d-flex justify-content-between align-items-center btn">
      <%= link_to icon('fas', 'times', "Cancel"), listings_path, class: "btn" %>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/my_reservations.html.erb
<div class="container mt-5">
  <h1> <%= current_user.first_name %>, here are all your reservations: </h1>
</div>

<main>
  <div class="container">
      <% @reservations.each do |myreservation| %>
        <div class="card-trip p-4">
          <div class="card-product-infos">
            <p><%= icon('fas', 'calendar-alt') %> From <%= myreservation.starts_at %> to <%= myreservation.ends_at %></p>
            <p>Owner: <%= myreservation.user_id %></p> 
            <p>Listing: <%= myreservation.listing_id %></p>
          </div>
        </div>
      <% end %>
  </div>
</main>

app/views/users/show.html.erb
<div class="container text-center mt-5">
  <h1> Your Profile </h1> 
  <%= link_to icon('fas fa-edit', "Edit"), edit_user_path(current_user), class: "btn pt-0 pr-0 text-muted" %>
  <div class="m-3">
    <% if @user.avatar.attached? %>
      <%= cl_image_tag @user.avatar.key, class: "avatar-profile" %>
    <% else %>
      <img src="https://medgoldresources.com/wp-content/uploads/2018/02/avatar-placeholder-300x300.gif" alt="user-avatar" class="avatar-profile">
    <% end %>
  </div>
  <p> <strong>Name:</strong>  <%= @user.first_name %> </p>
  <p> <strong>Email:</strong>  <%= @user.email %> </p>
  <p> <strong>Phone number:</strong> <%= @user.phone_number %> </p>
</div>